#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE connector_1;
	GRANT ALL PRIVILEGES ON DATABASE connector_1 TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE connector_2;
	GRANT ALL PRIVILEGES ON DATABASE connector_2 TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE broker;
	GRANT ALL PRIVILEGES ON DATABASE broker TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE clearing_house;
	GRANT ALL PRIVILEGES ON DATABASE clearing_house TO $POSTGRES_USER;
EOSQL
