version: "3.9"

services:
  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  broker:
    image: ghcr.io/ids-basecamp/broker:v1.0.0-basecamp
    restart: always
    depends_on:
      - postgresql
    environment:
      WEB_HTTP_PORT: 13001
      WEB_HTTP_PATH: /api
      WEB_HTTP_DATA_PORT: 13002
      WEB_HTTP_DATA_PATH: /api/v1/data
      WEB_HTTP_IDS_PORT: 13003
      WEB_HTTP_IDS_PATH: /api/v1/ids
      WEB_HTTP_MANAGEMENT_PORT: 13004
      WEB_HTTP_MANAGEMENT_PATH: /
      EDC_IDS_ID: urn:connector:broker
      EDC_IDS_TITLE: 'truzzt IDS BaseCamp Broker'
      EDC_IDS_DESCRIPTION: "Truzzt's IDS BaseCamp Broker"
      EDC_IDS_ENDPOINT: $BROKER_DOMAIN/api/v1/ids
      IDS_WEBHOOK_ADDRESS: $BROKER_DOMAIN
      EDC_IDS_CURATOR: http://truzzt.com
      EDC_IDS_MAINTAINER: http://truzzt.com
      EDC_CONNECTOR_NAME: truzzt-example-connector
      EDC_HOSTNAME: $BROKER_DOMAIN
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,x-api-key'
      EDC_WEB_REST_CORS_ORIGINS: '*'
      EDC_FLYWAY_REPAIR: 'false'
      EDC_DATASOURCE_DEFAULT_URL: $BROKER_POSTGRES_URL
      EDC_DATASOURCE_DEFAULT_USER: $POSTGRES_USER
      EDC_DATASOURCE_DEFAULT_PASSWORD: $POSTGRES_PASSWORD
      EDC_VAULT: /resources/vault.properties
      EDC_KEYSTORE: /resources/broker.jks
      EDC_KEYSTORE_PASSWORD: password
      EDC_OAUTH_CERTIFICATE_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_CLIENT_ID: 18:10:72:F0:2D:07:10:94:C4:16:93:21:54:15:09:46:20:B1:F2:E2:5B:57:F7:61:16:B2:B0:13:49:59:70:34:45:44:90:51:24:4A:1C:09
      EDC_OAUTH_TOKEN_URL: $DAPS_URL/token
      EDC_OAUTH_PROVIDER_JWKS_URL: $DAPS_URL/jwks.json
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL

      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 5
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 5
      EDC_CATALOG_CACHE_PARTITION_NUM_CRAWLERS: 60
    volumes:
      - ./resources:/resources

  connector_1:
    depends_on:
      - postgresql
    image: ghcr.io/ids-basecamp/connector:v1.0.0-basecamp
    environment:
      WEB_HTTP_PORT: 9191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 9192
      WEB_HTTP_MANAGEMENT_PATH: /api/v1/management
      WEB_HTTP_DATA_PORT: 9292
      WEB_HTTP_DATA_PATH: /api/v1/data
      WEB_HTTP_IDS_PORT: 9293
      WEB_HTTP_IDS_PATH: /api/v1/ids
      EDC_API_AUTH_KEY: password

      EDC_DATASOURCE_DEFAULT_NAME: default
      EDC_DATASOURCE_DEFAULT_URL: $CONNECTOR_1_POSTGRES_URL
      EDC_DATASOURCE_DEFAULT_USER: $POSTGRES_USER
      EDC_DATASOURCE_DEFAULT_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_DATAPLANEINSTANCE_NAME: dataplaneinstance
      EDC_DATASOURCE_DATAPLANEINSTANCE_URL: $CONNECTOR_1_POSTGRES_URL
      EDC_DATASOURCE_DATAPLANEINSTANCE_USER: $POSTGRES_USER
      EDC_DATASOURCE_DATAPLANEINSTANCE_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_ASSET_NAME: asset
      EDC_DATASOURCE_ASSET_URL: $CONNECTOR_1_POSTGRES_URL
      EDC_DATASOURCE_ASSET_USER: $POSTGRES_USER
      EDC_DATASOURCE_ASSET_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_CONTRACTDEFINITION_NAME: contractdefinition
      EDC_DATASOURCE_CONTRACTDEFINITION_URL: $CONNECTOR_1_POSTGRES_URL
      EDC_DATASOURCE_CONTRACTDEFINITION_USER: $POSTGRES_USER
      EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_CONTRACTNEGOTIATION_NAME: contractnegotiation
      EDC_DATASOURCE_CONTRACTNEGOTIATION_URL: $CONNECTOR_1_POSTGRES_URL
      EDC_DATASOURCE_CONTRACTNEGOTIATION_USER: $POSTGRES_USER
      EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_POLICY_NAME: policy
      EDC_DATASOURCE_POLICY_URL: $CONNECTOR_1_POSTGRES_URL
      EDC_DATASOURCE_POLICY_USER: $POSTGRES_USER
      EDC_DATASOURCE_POLICY_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_TRANSFERPROCESS_NAME: transferprocess
      EDC_DATASOURCE_TRANSFERPROCESS_URL: $CONNECTOR_1_POSTGRES_URL
      EDC_DATASOURCE_TRANSFERPROCESS_USER: $POSTGRES_USER
      EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD: $POSTGRES_PASSWORD

      EDC_CLEARINGHOUSE_LOG_URL:
      BROKER_CLIENT_EXTENSION_ENABLED: "false"
      EDC_BROKER_BASE_URL:

      EDC_OAUTH_CERTIFICATE_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_CLIENT_ID: 18:10:72:F0:2D:07:10:94:C4:16:93:21:54:15:09:46:20:B1:F2:E2:5B:57:F7:61:16:B2:B0:13:49:59:70:34:45:44:90:51:24:4A:1C:09
      EDC_OAUTH_TOKEN_URL: $DAPS_URL/token
      EDC_OAUTH_PROVIDER_JWKS_URL: $DAPS_URL/jwks.json
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL

      EDC_KEYSTORE: /resources/connector1.jks
      EDC_KEYSTORE_PASSWORD: password
      EDC_VAULT: /resources/vault.properties
    volumes:
      - ./resources:/resources
    ports:
      - "9001:9191"
      - "9002:9192"
      - "9003:9292"
      - "9004:9293"

  connector_2:
    depends_on:
      - postgresql
    image: ghcr.io/ids-basecamp/connector:v1.0.0-basecamp
    environment:
      WEB_HTTP_PORT: 9191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 9192
      WEB_HTTP_MANAGEMENT_PATH: /api/v1/management
      WEB_HTTP_DATA_PORT: 9292
      WEB_HTTP_DATA_PATH: /api/v1/data
      WEB_HTTP_IDS_PORT: 9293
      WEB_HTTP_IDS_PATH: /api/v1/ids
      EDC_API_AUTH_KEY: password

      EDC_DATASOURCE_DEFAULT_NAME: default
      EDC_DATASOURCE_DEFAULT_URL: $CONNECTOR_2_POSTGRES_URL
      EDC_DATASOURCE_DEFAULT_USER: $POSTGRES_USER
      EDC_DATASOURCE_DEFAULT_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_DATAPLANEINSTANCE_NAME: dataplaneinstance
      EDC_DATASOURCE_DATAPLANEINSTANCE_URL: $CONNECTOR_2_POSTGRES_URL
      EDC_DATASOURCE_DATAPLANEINSTANCE_USER: $POSTGRES_USER
      EDC_DATASOURCE_DATAPLANEINSTANCE_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_ASSET_NAME: asset
      EDC_DATASOURCE_ASSET_URL: $CONNECTOR_2_POSTGRES_URL
      EDC_DATASOURCE_ASSET_USER: $POSTGRES_USER
      EDC_DATASOURCE_ASSET_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_CONTRACTDEFINITION_NAME: contractdefinition
      EDC_DATASOURCE_CONTRACTDEFINITION_URL: $CONNECTOR_2_POSTGRES_URL
      EDC_DATASOURCE_CONTRACTDEFINITION_USER: $POSTGRES_USER
      EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_CONTRACTNEGOTIATION_NAME: contractnegotiation
      EDC_DATASOURCE_CONTRACTNEGOTIATION_URL: $CONNECTOR_2_POSTGRES_URL
      EDC_DATASOURCE_CONTRACTNEGOTIATION_USER: $POSTGRES_USER
      EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_POLICY_NAME: policy
      EDC_DATASOURCE_POLICY_URL: $CONNECTOR_2_POSTGRES_URL
      EDC_DATASOURCE_POLICY_USER: $POSTGRES_USER
      EDC_DATASOURCE_POLICY_PASSWORD: $POSTGRES_PASSWORD

      EDC_DATASOURCE_TRANSFERPROCESS_NAME: transferprocess
      EDC_DATASOURCE_TRANSFERPROCESS_URL: $CONNECTOR_2_POSTGRES_URL
      EDC_DATASOURCE_TRANSFERPROCESS_USER: $POSTGRES_USER
      EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD: $POSTGRES_PASSWORD

      EDC_CLEARINGHOUSE_LOG_URL:
      BROKER_CLIENT_EXTENSION_ENABLED: "false"
      EDC_BROKER_BASE_URL:

      EDC_OAUTH_CERTIFICATE_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_CLIENT_ID: 18:10:72:F0:2D:07:10:94:C4:16:93:21:54:15:09:46:20:B1:F2:E2:5B:57:F7:61:16:B2:B0:13:49:59:70:34:45:44:90:51:24:4A:1C:09
      EDC_OAUTH_TOKEN_URL: http://85.215.159.70:4567/token
      EDC_OAUTH_PROVIDER_JWKS_URL: http://85.215.159.70:4567/jwks.json
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL

      EDC_KEYSTORE: /resources/connector2.jks
      EDC_KEYSTORE_PASSWORD: password
      EDC_VAULT: /resources/vault.properties
    volumes:
      - ./resources:/resources
    ports:
      - "9005:9191"
      - "9006:9192"
      - "9007:9292"
      - "9008:9293"
